'use strict';
(() => {
  const el = id => document.getElementById(id);
  const hex = n => '0x' + (n >>> 0).toString(16).padStart(8, '0');
  const mem = {count:256, playing:false, elapsed:0, scenario:'good', selected:101, open:new Set([3])};
  const para = s => `<p>${s}</p>`;
  const code = s => `<pre><code>${esc(s)}</code></pre>`;
  const table = (heads,rows) => `<table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  function source(file, program) {
    let text = window.firmwareSources[file] || 'This module is not loaded in this mode.';
    if(program){const begin=text.indexOf('.program '+program+'\n');if(begin>=0){text=text.slice(begin);const end=text.indexOf('\n.program ');if(end>=0)text=text.slice(0,end);text=text.split('% c-sdk')[0];}}
    return `<details><summary>View source: ${esc(program||file)}</summary><div class="source-meta"><span>Demo source snapshot · not executed</span><a href="../../src/${file}">Open ${file} ↗</a></div>${code(text)}</details>`;
  }
  el('memory-lab').innerHTML=`<div class="panel-heading"><div><span class="eyebrow">Inspect every FSS sample bit</span><h2>GPIO → ISR → FIFO → DMA → memory</h2></div><span class="chip">8 words × 32 bits</span></div><p class="detail-intro">The marker contains 15 consecutive ones. Expand a word and select any bit to inspect its sample position, register bit, and memory byte. This view zooms into the runtime phase window; acquisition differences are explained below.</p>
  <p id="mem-mode-note" class="bit-guidance"></p><div class="pipeline"><span id="pipe-pin">GP10 / IN</span><span id="pipe-isr">ISR / shift left</span><span id="pipe-fifo">32-bit autopush</span><span id="pipe-dma">DREQ / DMA</span><span id="pipe-validate">CLZ / validate</span></div>
  <div class="detail-toolbar"><button id="mem-play">↺ Sample bit by bit</button><button id="mem-bit">Next bit</button><button id="mem-word">Next word</button><button id="mem-complete">Full snapshot</button><button id="mem-aligned">Position 101 example</button><label>Scenario <select id="mem-scenario"><option value="good">Valid 15-bit marker</option><option value="cross">Cross-word: starts at 125</option><option value="short">Incomplete: only 14 ones</option><option value="double">Extra second marker</option><option value="expired">Valid marker, expired DMA window</option><option value="outside">Complete marker, outside tolerance</option><option value="missing">Missing marker</option></select></label></div>
  <div class="memory-scrub"><label for="mem-progress">Sampled</label><input id="mem-progress" type="range" min="0" max="256" value="256"><output id="mem-count">256 / 256</output></div>
  <div class="memory-layout"><div><div id="memory-words"></div><p class="bit-guidance">Samples run left to right, bit31 to bit0. Uncommitted words show “not written”; old memory is not assumed to be zero. RX FIFO-to-DMA latency is simplified as immediate service here.</p></div><div class="memory-side"><div class="memory-card"><h3>Current ISR / DMA</h3><div id="mem-registers"></div></div><div class="memory-card"><h3>Selected bit</h3><div id="mem-selected"></div></div><div class="memory-card"><h3>Position and correction</h3><div id="mem-calculation"></div></div><div id="mem-validation" class="validation"></div></div></div>
  <details class="detail-entry"><summary>Why do 32-bit words and little-endian memory bytes appear in different orders?</summary><div class="detail-content">${para('Sample time order starts at bit31. DMA writes 32-bit words, while RP2350 little-endian memory stores the least significant byte first. Thus word3=0x07fff000 appears as 00 f0 ff 07 at offsets +12..+15. Endianness changes byte address order, not sample bit order. Reading from the lowest-address byte does not directly give sample time order.')}${para('Every 32 IN instructions trigger autopush and reset the shift count. The animation shows valid bits shifted into the current word, without assuming residual raw ISR contents are zero. The real receive streamer instead uses 8-bit autopush; these are different paths.')}${source('flexray_fss_timing.pio','flexray_fss_phase_sampler')}</div></details>`;
  function samples(){
    const first=mem.scenario==='cross'?125:mem.scenario==='outside'?140:101+state.phase;
    const width=mem.scenario==='short'?14:15;
    const bits=Array.from({length:256},(_,i)=>mem.scenario==='missing'?0:Number(i>=first&&i<first+width));
    if(mem.scenario==='double')for(let i=190;i<205;i++)bits[i]=1;
    const words=Array.from({length:8},(_,w)=>bits.slice(w*32,w*32+32).reduce((n,b)=>((n<<1)|b)>>>0,0));
    return {bits,words,first};
  }
  function renderMemory(){
    const {bits,words}=samples(), first=bits.indexOf(1), full=Math.floor(mem.count/32), count=mem.count%32;
    el('mem-mode-note').textContent=state.mode==='dual'?'The diagram above shows four-channel OFF, which has no frame generation capture/phase. This separate static frame generation memory lab does not run in four-channel firmware.':state.mode==='single'?'The diagram above follows MITM. This separate view shows runtime phase memory for static frame generation; MITM does not use it to authorize injection.':'Linked to the phase offset above. Special scenarios affect only this memory lab, not a real device.';
    el('mem-count').textContent=`${mem.count} / 256`;el('mem-progress').value=mem.count;el('mem-play').textContent=mem.playing?'Ⅱ Pause sampling':mem.count===256?'↺ Sample bit by bit':'▶ Continue sampling';
    el('memory-words').innerHTML=words.map((word,w)=>`<details class="memory-word ${w>=full?'pending':''}" data-word="${w}" ${mem.open.has(w)?'open':''}><summary><span>word[${w}]</span><small>sample ${w*32}…${w*32+31}</small><b>${w<full?hex(word):'not written'}</b></summary><div class="bit-row">${bits.slice(w*32,w*32+32).map((b,k)=>{const i=w*32+k;return `<button class="bit ${b?'one':''} ${i>=mem.count?'future':''} ${i===mem.selected?'chosen':''}" data-bit="${i}" aria-label="sample ${i}, word ${w}, bit ${31-k}, value ${i<mem.count?b:'not sampled'}" title="sample ${i} → bit${31-k}">${i<mem.count?b:'·'}</button>`}).join('')}</div><div class="byte-view"><span>+${w*4}…+${w*4+3} bytes (LE)</span><span>${w<full?[0,8,16,24].map(s=>((word>>>s)&255).toString(16).padStart(2,'0')).join(' '):'-- -- -- --'}</span><span>Full value ${hex(word)} ${w<full?'':'(expected illustration)'}</span></div></details>`).join('');
    let current=0;for(let i=full*32;i<mem.count;i++)current=((current<<1)|bits[i])>>>0;
    el('mem-registers').innerHTML=`<p>Valid bits in current word <code>${hex(current)}</code></p><p>ISR shift count <code>${count} / 32</code></p><p>autopush <code>${full}</code> pushes · committed <code>${full*4}</code> bytes</p><p>${count===0&&mem.count?'A complete word was just pushed; the count resets to zero.':'RX FIFO push occurs only after 32 IN instructions.'}</p>`;
    const i=mem.selected,w=Math.floor(i/32),b=31-i%32;
    el('mem-selected').innerHTML=`<p>sample <code>${i}</code> → word[<code>${w}</code>].bit<code>${b}</code></p><p>Memory byte offset <code>+${w*4+Math.floor(b/8)}</code>, byte bit <code>${b%8}</code></p><p>Value <code>${i<mem.count?bits[i]:'not yet sampled'}</code> · ${w<full?'DMA committed':'word not yet written'}</p>`;
    const fw=first<0?-1:Math.floor(first/32), clz=first<0?32:Math.clz32(words[fw]),error=first-101;
    const exact=first>0&&first+15<256&&bits.every((v,i)=>v===Number(i>=first&&i<first+15));
    let result='Accept: this marker allows tail = nominal + '+error,status='';
    if(mem.count<256){result='Wait: the first 8 words are not all committed. Old memory cannot represent this capture.';status='pending';}
    else if(!exact){result='Reject: exactly one complete 15-bit marker is required, with clear space on both sides.';status='invalid';}
    else if(Math.abs(error)>32){result='Reject: the marker is complete, but error exceeds the ±32-clock tolerance.';status='invalid';}
    else if(mem.scenario==='expired'){result='Reject: the memory marker is valid, but the finite DMA window has expired. Leave the tail unchanged.';status='invalid';}
    el('mem-calculation').innerHTML=`<p>${first<0?'No nonzero word':`first = <code>${fw} × 32 + clz(${hex(words[fw])})</code><br>= <code>${fw} × 32 + ${clz} = ${first}</code>`}</p><p>expected <code>8×15 − 19 − 0 = 101</code></p><p>error <code>${first<0?'unavailable':`${first} − 101 = ${error}`}</code></p><p>Shape validation checks all 8 words, including markers spanning word boundaries.</p>`;
    if(mem.count<256)el('mem-calculation').innerHTML='<p>The first 8 words are not all committed. CLZ and shape checks must wait.</p><p>The scenario waveform is known, but future samples cannot be treated as committed DMA results.</p>';
    el('mem-validation').className='validation '+status;el('mem-validation').textContent=result;
    document.querySelectorAll('.pipeline span').forEach(x=>x.classList.remove('current'));
    el(mem.count===256?'pipe-validate':count===0&&mem.count?'pipe-dma':'pipe-isr').classList.add('current');
  }
  el('memory-words').addEventListener('toggle',e=>{const w=e.target.dataset.word;if(w!==undefined){if(e.target.open)mem.open.add(Number(w));else mem.open.delete(Number(w));}},true);
  el('memory-words').addEventListener('click',e=>{const b=e.target.closest('[data-bit]');if(b){mem.selected=Number(b.dataset.bit);renderMemory();}});
  function scrub(n){mem.count=Math.max(0,Math.min(256,n));mem.playing=false;renderMemory();}
  el('mem-play').onclick=()=>{if(mem.count===256)mem.count=0;mem.playing=!mem.playing;mem.elapsed=0;renderMemory();};
  el('mem-bit').onclick=()=>scrub(mem.count+1);el('mem-word').onclick=()=>scrub((Math.floor(mem.count/32)+1)*32);el('mem-complete').onclick=()=>scrub(256);
  el('mem-progress').oninput=e=>scrub(Number(e.target.value));
  el('mem-scenario').onchange=e=>{mem.scenario=e.target.value;mem.count=256;mem.playing=false;mem.open=new Set(e.target.value==='cross'?[3,4]:[3]);renderMemory();};
  el('mem-aligned').onclick=()=>{state.phase=0;el('phase').value=0;mem.scenario='good';el('mem-scenario').value='good';mem.count=256;mem.playing=false;mem.open=new Set([3]);render();};
  let last=0;function tick(t){const dt=Math.min(t-last,100);last=t;if(mem.playing&&!document.hidden){mem.elapsed+=dt; if(mem.elapsed>=24){const n=Math.floor(mem.elapsed/24);mem.elapsed%=24;mem.count=Math.min(256,mem.count+n);if(mem.count===256)mem.playing=false;renderMemory();}}requestAnimationFrame(tick);}requestAnimationFrame(tick);
  const entries=[
    ['capture','FSS capture: GPIO, WAIT, IRQ, and 15 ones',para('PIO2 SM3 reads the selected RXD and same-side TXEN. After qualifying idle HIGH, it waits for TSS LOW and TXEN HIGH, confirms RXD is still LOW, then waits for FSS HIGH. IRQ next0 sends the bootstrap event to PIO0. Side-set holds GP10 HIGH for 15 clocks, then PUSH drives it LOW. The RX FIFO token pairs with a real header; it is not a DMA timestamp.')+code('GP26 → PIO2 SM3 → GP10 HIGH ×15\nGP10 → PIO0 SM1(measure) / SM3(phase)\nOne bit per clock → 000…111111111111111…000')+para('The 6-clock idle check avoids aliasing when short BSS LOW intervals fall between the old 15-clock checks. The WAIT edge sequence is retained. Capture uses 10 words; the real RX streamer idle check was not changed to 6 clocks.')+source('flexray_fss_timing.pio','flexray_fss_capture')],
    ['measure','Acquisition: ring buffer, CTZ, and the lowest five observed IDs',para('Acquisition uses a single IN instruction on PIO0 SM1 and a 1024-word / 4 KiB DMA ring. measured_stamp() skips the newest 8 words, searches backward through safe data for a nonzero word, and uses CTZ to locate the last HIGH sample as a decreasing timestamp. Differences between matching edges of fixed 15-clock markers equal FSS intervals. Runtime instead uses CLZ to locate the first HIGH; these algorithms serve different purposes.')+code('Acquisition: stamp = −(word_index×32 + 31 − ctz(word))\nRuntime: first = word_index×32 + clz(word)\nslot = Δtime / ΔID\ncycle = (Δtime − ΔID×slot) / Δcycle')+para('Retain only the lowest five distinct observed static FIDs; missing slots still occupy time. Use a 32-sample median, with 12 qualifying samples required by default. A new lower ID replaces the largest candidate; candidates freeze at lock. Automatic slot measurement needs at least two distinct IDs in one cycle. Synchronization loss clears candidates.')+source('flexray_slot_schedule.c')],
    ['phase','Phase calibration: 8 words, a finite deadline, and rejection rules',para('The first 256 clocks cover marker shape validation, not the entire DMA lifetime. DMA keeps running to enforce a hardware deadline during CPU processing. Before writing the tail, check transfer_count, ring overwrite, and RXSTALL again.')+code('phase_words = (slot_cycles×3/4 − 96) / 32\nwindow_open: remaining > 0 && done >= 8 && done < 1024\nexpected = local_tss_cycles − 19 − phase_cycles\nAccept exactly one complete 15-bit marker, |error| <= tolerance')+para('The second deadline check is retained. Ones remaining in memory do not authorize calibration: expired DMA, overwritten samples, incomplete or extra markers, wrong labels, or excessive error all prevent tail updates. publish() runs in SRAM to avoid spending the valid window on flash latency.')+source('flexray_fss_timing.pio','flexray_fss_phase_sampler')+source('flexray_frame_gen.c')],
    ['pace','Pace schedule: guards, tail, and one-time correction',para('At lock, the 1-word measure program becomes the 16-word pace program, and SM3 loads the 2-word phase program. Hardware FSS starts an initial countdown of about one cycle; the CPU only binds reference labels and loads the table. Every static slot has a beat, including empty slots. The tail has none.')+code('slot entry = slot_cycles − 9\n0 → 64 guards (one slot total, no pace) → 0\nnominal_tail = cycle − max_id×slot − 13\nperiods[gap_index] = nominal_tail + correction\npace DMA → tail reset DMA → reload DMA')+para('Only the next cycle boundary changes. Guards prevent early tail prefetch; reset restores the nominal value after consumption. Missing references do not reapply old corrections. Static intervals stay fixed, without an unbounded integrating PLL.')+source('flexray_fss_timing.pio','flexray_slot_pace')],
    ['packet','Templates: single-use payloads, null, dual banks, and CRCs',para('Each target has one null template and two normal banks. Each template stores a 268-byte packet plus 64 three-byte CRCs, totaling 460 bytes. Six templates across two targets total 2760 bytes. Core0 builds an inactive bank; core1 applies the target mailbox when prepared_packet is not held.')+code('Slot B prepares C: choose template → write cycle / three CRC bytes\nPreload packet DMA → publish pulse DMA → hardware beat C starts TX\nAfter independent C DONE: release packet → prepare adjacent D')+para('Normal data is consumed only when cycle&3=3. Other cycles send null and retain pending data. Stopping host submissions does not replay the last normal frame. Only the 18-byte null payload is zero; NFI/PPI=0 and FID/length/cycle/CRC remain valid. Pending data has no wall-clock expiry. Prepared packets cannot change until DONE; DMA completion is not wire completion.')+source('flexray_frame_gen_packet.c')+source('flexray_frame_gen_rules.h')],
    ['output','Transmission: framing descriptors, GP16, GP17, TXEN, and DONE',para('The inducer emits framing only; actual packet bytes come from a separate DMA. Descriptor bit 0 selects the level; the upper 31 bits encode clocks−5. The sequence includes TSS, FSS/first BSS, per-byte BSS/placeholder data, FES, and 165-clock idle, followed by a terminal value of 1. The original injector enters at WAIT TSS offset 3 and does not drive shared TXD HIGH during initialization.')+code('PIO0 SM1 IRQ3 → PIO0 SM0\nSM0: PIO1 IRQ7 SET + GP17 LOW → GP16 TSS\nPIO1 SM2: WAIT GP17 LOW; SET GP5 LOW\nPIO2 SM2: GP16 framing + packet FIFO → GP4\nFES + 11bit idle → IRQ7 CLEAR + GP17 HIGH → PIO0 IRQ2')+para('PIO1 already owns TXEN; PIO0 hands ownership over through GP17. The four-instruction WAIT/SET controller leaves the pin untouched during WAIT, preserving real forwarding. GP17 has a legacy RELAY name during main startup, but static runtime uses it for PIO0 ownership, not separate relay control.')+source('flexray_frame_gen_output.pio')],
    ['irq','IRQ map: PIO flags and CPU IRQs use different numbering',table(['PIO flag','Producer → consumer','Meaning'],[['PIO0 0','PIO2 capture irq next → pace WAIT','bootstrap FSS'],['PIO0 3','pace → inducer','Trigger each static slot'],['PIO0 4','pace → phase','Start bounded sampling'],['PIO0 5','pace → CPU PIO0_IRQ_0','consume / prepare / watchdog'],['PIO0 2','inducer → CPU PIO0_IRQ_1','frame generation DONE'],['PIO1 7','Real streamer / cross-PIO frame generation','Echo exclusion'],['PIO1 4 / 3','Real streamer → CPU','Real header / frame-end'],['PIO0 4 / 3 (OFF)','FR3/4 streamer → CPU','Second pair real header / frame-end']])+para('ON/OFF are mutually exclusive, so PIO0 flags 3/4 serve different purposes in each firmware. Frame generation completion uses only PIO0 flag2, not a real frame-end combined with ACTIVE state to infer the source.')],
    ['dma','DMA map: 10 channels, finite transfers, and reuse',table(['Function','ON channels','Source → destination'],[['Real RX','2','PIO1 RX FIFO → two rings'],['MITM packet','2','Templates → two original injectors'],['sample','1','Acquisition SM1 or phase SM3 → same ring'],['pace / reset / reload','3','Schedule → FIFO; reset tail; reload address'],['pulse','1','Finite framing → PIO0 SM0'],['frame generation packet','1','Finite packet → PIO2 SM2']])+para('DMA channel numbers are dynamically claimed, not fixed interfaces. ON uses 10; OFF uses 4 RX + 4 MITM = 8. Packet/pulse DMA does not replay cyclically; only the pace schedule loops. Disable the relevant channels before aborting chained DMA to address RP2350-E5.')],
    ['recovery','Sleep/loss: three cycles, generations, and completion races',para('About three cycles without valid calibration trigger reason1; an actual cycle discontinuity triggers reason2. Header-time slot mismatches are diagnostic only; CPU arrival time never replaces FSS. On loss, stop pace, clear triggers, and wait 1 microsecond in the exceptional path for in-flight triggers to settle.')+code('local_active = prepared_packet && (GP17 LOW || DONE pending)\nsync_generation++ → Invalidate stale payload / mailbox generations\nActive frame finishes via independent DONE → reacquire → valid phase → resume')+para('Recovery retains enable intent, not stale payloads. New payloads are rejected while unsynchronized. The reason field retains the latest reason, not a fault history. Status is a diagnostic snapshot, not a per-action acknowledgment or an atomic snapshot of every field at one instant.')],
    ['mitm','MITM: real triggers, caching, failsafe, and bridge modes',para('The primary FID6/base2 header calls prepare_inject_frame: use the FID8 cache, consume a valid override, replace only the first four payload bytes, and update cycle/CRC. Real frame-end calls inject_prepared_frame, rechecks command ownership and expiry, then arms the target DMA. Real target TSS/FSS drives the original injector; missing targets do not generate new frames.')+table(['Mode','RX SM','Target rule / output'],[['ON single bridge','PIO1 SM0/1','FID8 → FR1, PIO2 SM0'],['OFF dual bridge','PIO1 SM0/1 + PIO0 SM0/1','FID8 → FR3, PIO2 SM2']])+para('In OFF, secondary headers identify sources; the primary header prepares the current rule. Missing overrides preserve forwarding, while frame generation sends null without payloads. Mailboxes, triggers, and DMA are independent. Existing MITM locks remain; frame generation adds no locks. This does not mean the entire firmware is lock-free.')+source('flexray_injector_rules.h')+source('flexray_forwarder_with_injector.pio')],
    ['streamer','Real streamer: 8-bit autopush, two reductions, and residual bits',para('ON/OFF share the 28-word streamer; the old 30-word version remains only as a test baseline. First, JMP Y-- already underflows 0 to UINT32_MAX, so MOV Y,!NULL is removed and IRQ4 gains one clock. Second, natural frame-end follows complete 8-bit autopush, so MOV ISR,NULL is removed and the preceding WAIT gains one clock. RX bytes, IRQ timing, and TXEN timing are preserved.')+para('Resetting the shift count does not zero the raw ISR. Existing paths shift in a complete next byte without stale bits. Any future partial-byte abort into frame-end requires another review. The 3455 mutation cases include a forced partial-byte exit counterexample. This is model validation, not exhaustive electrical coverage of malformed inputs.')+source('flexray_bss_streamer.pio')],
    ['gpio','GPIO and instruction space: the role of each SM',para('Select any of the 12 SMs above to view its PIO program. Four SMs share 32 words per PIO; multiple SMs can reuse a program. An unused SM does not imply free instruction space. ON PIO0 uses 13 words during acquisition and 30 at runtime; PIO1=28+4=32 and PIO2=22+10=32. OFF uses 28/28/22 words.')+table(['Signal','GPIO','Drive / read'],[['FR1 RXD / TXD / TXEN','26 / 28 / 27','PIO1 RX / PIO2 TX / PIO1 EN'],['FR2 RXD / TXD / TXEN','6 / 4 / 5','PIO1 RX / PIO2 TX / PIO1 EN'],['FSS marker (ON)','10','PIO2 SM3 → PIO0 sampling'],['Framing (ON)','16','PIO0 SM0 → PIO2 SM2'],['ownership (ON)','17','PIO0 SM0 → PIO1 SM2 / CPU'],['FR3 RXD / TXD / TXEN (OFF)','8 / 10 / 9','PIO0 RX / PIO2 TX / PIO0 EN'],['FR4 RXD / TXD / TXEN (OFF)','21 / 16 / 22','PIO0 RX / PIO2 TX / PIO0 EN']])+source('board_config.h')],
    ['host','Host wire format, BUSY, and boundaries',code('0x94: [94][FID u16 LE][base u8][length u16 LE][payload]\nC: 94 0c 00 03 12 00 + 18 bytes\nD: 94 0d 00 03 12 00 + 18 bytes\n0x95: [95][0/1] → disable/enable frame generation')+para('USB bulk OUT03 and NCM UDP5501 use the same action parser. C/D each have a publication mailbox. A pending publication for the same target returns internal BUSY without overwrite; applied but unconsumed data may be replaced. 0x94/95 provide no ACK or retry. Status last_error is not a per-action acknowledgment. Apply enable separately first; before pacing, real headers service commands.')+para('Diagnostics A0..A4 use NCM request/reply; A0 cannot change compiled rules. UDP input is limited to 263 bytes, so concatenated actions must fit. USB transfers with lengths divisible by 64 need end-of-transfer ZLP handling. Split actions are not reassembled across input buffers.')],
    ['evidence','Review and validation: evidence and limits',para('Memory examples follow the current C algorithm: default position 101 gives word3=0x07fff000. Separate scenarios show cross-word, incomplete, extra-marker, out-of-tolerance, and expired captures. Page state is illustrative and does not read a device.')+para('This branch retains the original FlexRay PIO and frame build timing implementation. Host regression tests and ON/OFF builds passed. Renewed electrical bench validation has not been performed. The page is educational and does not read a device.')+'<a href="../../docs/bench-validation.md">Validation summary ↗</a>']
  ];
  el('detail-library').innerHTML=`<div class="panel-heading"><div><span class="eyebrow">Explore the implementation</span><h2>From concepts to registers and source</h2></div><div class="detail-toolbar"><button id="expand-all">Expand all</button><button id="collapse-all">Collapse all</button></div></div><p class="detail-intro">Expand each topic independently. Source is an offline, read-only snapshot. The selected mode, SM, and step remain in the demo above.</p><nav class="detail-nav">${entries.map(([id,title])=>`<a href="#detail-${id}" data-detail="${id}">${esc(title.split(':')[0])}</a>`).join('')}</nav>${entries.map(([id,title,body])=>`<details id="detail-${id}" class="detail-entry"><summary>${esc(title)}</summary><div class="detail-content">${body}</div></details>`).join('')}`;
  function openDetail(id){const target=el('detail-'+id);target.open=true;target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
  el('expand-all').onclick=()=>el('detail-library').querySelectorAll('.detail-entry').forEach(d=>d.open=true);
  el('collapse-all').onclick=()=>el('detail-library').querySelectorAll('details').forEach(d=>d.open=false);
  el('detail-library').addEventListener('click',e=>{const a=e.target.closest('[data-detail]');if(a){e.preventDefault();openDetail(a.dataset.detail);}});
  function smSource(){
    el('sm-source')?.remove();const selected=state.selected,dual=state.mode==='dual';let files=[];

    if(selected.startsWith('p2')&&(dual||selected!=='p2s3'))files=[['flexray_forwarder_with_injector.pio']];
    else if(['p1s0','p1s1'].includes(selected)||(dual&&['p0s0','p0s1'].includes(selected)))files=[['flexray_bss_streamer.pio']];
    else if(!dual){const map={p0s0:['flexray_frame_gen_output.pio','flexray_frame_gen_inducer'],p0s1:['flexray_fss_timing.pio',roles().p0s1.name==='Measure'?'flexray_fss_sampler':'flexray_slot_pace'],p0s3:['flexray_fss_timing.pio','flexray_fss_phase_sampler'],p1s2:['flexray_frame_gen_output.pio','flexray_frame_gen_txen'],p2s3:['flexray_fss_timing.pio','flexray_fss_capture']};if(map[selected])files=[map[selected]];}
    const holder=document.createElement('div');holder.id='sm-source';holder.className='sm-source';holder.innerHTML=files.length?`<div class="source-meta">${esc(roles()[selected].name)} · View PIO instructions${roles()[selected].status==='reserved'?'(reserved, not loaded yet)':''}</div>${files.map(args=>source(...args)).join('')}`:'This SM is unused and has no separate program loaded. See the resource strip above for remaining shared instruction space.';document.querySelector('.inspector').append(holder);
  }
  [['memory',null],['cpu','irq'],['host','host'],['output','output'],['bus','capture']].forEach(([id,detail])=>{const target=el(id);target.setAttribute('role','button');target.tabIndex=0;target.title='View implementation details';const action=()=>detail?openDetail(detail):el('memory-lab').scrollIntoView({behavior:'smooth'});target.addEventListener('click',action);target.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();action();}});});
  const button=document.createElement('button');button.className='detail-jump';button.textContent='View this step in source ↓';button.onclick=()=>openDetail(state.sleeping?'recovery':state.mode!=='frame-gen'?'mitm':['capture','measure','pace','packet','output','output','phase','pace','recovery'][state.step]);document.querySelector('.explanation').append(button);
  document.addEventListener('demo:change',()=>{renderMemory();smSource();});document.addEventListener('demo:inspect',smSource);renderMemory();smSource();
})();
